id: IFDB0D1F7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T13:27:59+00:00'
last_modified: '2022-06-08T16:55:27.784855+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6164
  title: བོད་སྐད་རླུང་འཕྲིན་བརྙན་འཕྲིན་གྱི་བཤད་མཁན་དང་འགོ་འཛིན་པའི་ཤེས་བྱ་བློ་གསལ་མགུལ་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    4EF4:
      image_group_id: I1KG8431
      title: ''
      total_pages: 354
      order: 1
      base_file: 4EF4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
