id: opecha:P010703
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG6164
  title: བོད་སྐད་རླུང་འཕྲིན་བརྙན་འཕྲིན་གྱི་བཤད་མཁན་དང་འགོ་འཛིན་པའི་ཤེས་བྱ་བློ་གསལ་མགུལ་རྒྱན།
  volume: ''
  author: ''
