id: P010703
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG6164
  title: བོད་སྐད་རླུང་འཕྲིན་བརྙན་འཕྲིན་གྱི་བཤད་མཁན་དང་འགོ་འཛིན་པའི་ཤེས་བྱ་བློ་གསལ་མགུལ་རྒྱན།
  author: ''
  volumes:
    9cc52f71a52846748ffb2e06c8174c7f:
      image_group_id: I1KG8431
      title: ''
      volume_number: 1
      total_pages: 354
